// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: time_stream.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamTimeRequest) Reset() {
	*x = StreamTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTimeRequest) ProtoMessage() {}

func (x *StreamTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTimeRequest.ProtoReflect.Descriptor instead.
func (*StreamTimeRequest) Descriptor() ([]byte, []int) {
	return file_time_stream_proto_rawDescGZIP(), []int{0}
}

type StreamTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *StreamTimeResponse) Reset() {
	*x = StreamTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTimeResponse) ProtoMessage() {}

func (x *StreamTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTimeResponse.ProtoReflect.Descriptor instead.
func (*StreamTimeResponse) Descriptor() ([]byte, []int) {
	return file_time_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamTimeResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_time_stream_proto protoreflect.FileDescriptor

var file_time_stream_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28,
	0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x52, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x18, 0x5a, 0x16,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2d, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_time_stream_proto_rawDescOnce sync.Once
	file_time_stream_proto_rawDescData = file_time_stream_proto_rawDesc
)

func file_time_stream_proto_rawDescGZIP() []byte {
	file_time_stream_proto_rawDescOnce.Do(func() {
		file_time_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_time_stream_proto_rawDescData)
	})
	return file_time_stream_proto_rawDescData
}

var file_time_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_time_stream_proto_goTypes = []interface{}{
	(*StreamTimeRequest)(nil),  // 0: main.StreamTimeRequest
	(*StreamTimeResponse)(nil), // 1: main.StreamTimeResponse
}
var file_time_stream_proto_depIdxs = []int32{
	0, // 0: main.TimeService.StreamTime:input_type -> main.StreamTimeRequest
	1, // 1: main.TimeService.StreamTime:output_type -> main.StreamTimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_time_stream_proto_init() }
func file_time_stream_proto_init() {
	if File_time_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_time_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_time_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_time_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_time_stream_proto_goTypes,
		DependencyIndexes: file_time_stream_proto_depIdxs,
		MessageInfos:      file_time_stream_proto_msgTypes,
	}.Build()
	File_time_stream_proto = out.File
	file_time_stream_proto_rawDesc = nil
	file_time_stream_proto_goTypes = nil
	file_time_stream_proto_depIdxs = nil
}
